set -g default-command 'fish'
set -g default-shell 'fish'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'alexwforsythe/tmux-which-key'

bind-key -n M-g if-shell -F '#{==:#{session_name},scratch}' {
  detach-client
} {
  display-popup -d "#{pane_current_path}" -E "tmux new-session -A -s scratch"
}

set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @kanagawa-theme 'dragon'
set -g @kanagawa-plugins "git cpu-usage ram-usage"
set -g @kanagawa-ignore-window-colors true

set -g default-terminal "xterm-ghostty"
set -ga terminal-overrides ",xterm-ghostty:Tc"

set -s extended-keys on

set -g escape-time 0

set -g mode-keys vi
if-shell 'uname | grep -q Darwin' \
  'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"' \
  'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip"'

unbind C-b
set -g prefix C-a
bind C-a send-prefix

unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind d split-window -v -c "#{pane_current_path}"

set -g mouse on
set -g status-position top

bind K confirm-before -p "Kill all other sessions? (y/n)" "kill-session -a"

set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on

set -g focus-events on

run '~/.tmux/plugins/tpm/tpm'